name: Daily course crawling

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  process_data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.PAT }}
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run script
      run: bash scripts/update.sh
    - name: Commit report
      run: |
          git config --global user.name 'ChenKB91'
          git config --global user.email 'chenkb91@users.noreply.github.com'
          git commit -am "Automated commit"
          git push
